apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data-storage
  labels:
    app: neo4j
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-plugin-storage
  labels:
    app: neo4j
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /var/lib/neo4j/plugins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-plugin-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
